### ISSUE TITLE
End-of-Life (EoL) Definition

### ISSUE THREAD

**Issue by santosomar** [oasis-tcs/openeox#33]
We separated "End-of-life" in issues #27  and #30 . This issue will be used to define Software End-of-Life (EoL).

**Comment by p-rog** [comment]
When we were working with @thschaffr on the SEoS definition (proposal in https://github.com/oasis-tcs/openeox/issues/27#issuecomment-2275060899), we decided to also prepare the **Software End-of-Life (SEoL)** definition. Our proposal is generic and flexible enough to cover all possible use cases and it's directly connected with the SEoS definition. 

Like @thschaffr mentioned in https://github.com/oasis-tcs/openeox/issues/27, the product type like `Software`, `Hardware` or even `Managed Service` can be and should be part of the product metadata. It could be a mandatory field like `Product-Type` with different categories. In that case the proposed Software End-of-Life (EoL) definition can be renamed to for example "**xEnd-of-Life**" (**xEoL**).


### Suggestion for Software End-of-Life (SEoL):

> The Software End-of-Life (SEoL) indicates the last day when the particular product (or the product version/release) is officially supported in any way by the vendor. After this date there shouldn’t be more development, updates or any type of support expected from the vendor. The existing customers are also impacted by this product lifecycle stage and should consider migration to the still supported product version or release.

**Comment by santosomar** [comment]
As discussed on 2024-08-21 this is the current definition:

The End-of-Life (EoL) indicates the last day when the particular product (or the product version/release) is officially supported in any way by the vendor. After this date there shouldn’t be more development, updates or any type of support expected from the vendor. The existing customers are also impacted by this product lifecycle stage and should consider migration to the still supported product version or release.

**Comment by santosomar** [comment]
Motion passed: https://groups.oasis-open.org/discussion/motion-to-accept-the-end-of-life-eol-definition
