### ISSUE TITLE
Product Lifecycle definition

### ISSUE THREAD

**Issue by p-rog** [oasis-tcs/openeox#35]
When we were working with @thschaffr on the Software End-of-Sales (SEoS) (https://github.com/oasis-tcs/openeox/issues/27#issuecomment-2275060899) and the Software End-of-Life (SEoL) (https://github.com/oasis-tcs/openeox/issues/33#issuecomment-2275219644) definitions, we realized that we need also very clear definition what **Product Lifecycle** really is.  There is a high chance that people may have different expectations from the product lifecycle definition and well defined product lifecycle phases won't be good enough. We need to define what **Product Lifecycle** is.
Suggested product lifecycle definition is generic and covers software and hardware as well.

### Suggestion for Product Lifecycle

> With every product type (software, hardware, managed service and other deliverables) there can be an associated lifecycle model that may contain various support types (various levels of maintenance). The lifecycle support model changes over time from initial release (General Availability - GA) to the end of the maintenance - End-of-Life (EoL). During the product lifecycle the support types can switch from one to another or there can be multiple support types at the same time. It usually depends on the product type and vendor offer as well as related geographical regulations.

**Comment by thschaffr** [comment]
As discussed in the previous meeting, @p-rog and I worked on a draft proposal for the `Product Lifecycle` definition.

> Every product type (software, hardware, managed service and other deliverables) can be associated with a lifecycle model that contains definitions of various support models (different levels of maintenance) in association to the product versioning convention. The lifecycle support model is dynamic and changes over time, from the product's initial release (General Availability) to its discontinuation (End-of-Life). During the product lifecycle, support types switch from one state to another and may even run in parallel to meet individual requirements. Those requirements may depend on the product type, the vendor offerings, as well as geographical related regulations.

We are looking forward to the input from the TC.
Thank you.

**Comment by thschaffr** [comment]
The motion to accept the [definition](https://github.com/oasis-tcs/openeox/issues/35#issuecomment-2331322433) above is available at:
https://groups.oasis-open.org/discussion/motion-to-accept-the-product-lifecycle-definition
