### ISSUE TITLE
Vendor definition

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/openeox#37]
As discussed in today's TC meeting, we should define the vendor. Here is the definition of CSAF as a starting point:

_**vendor**: the community, individual, or organization that created or maintains a product (including open source software and hardware providers)_

**Comment by tschmidtb51** [comment]
We might need to also add something about services:

_**product**: is any deliverable (e.g. software, hardware, specification,...) which can be referred to with a name. This applies regardless of the origin, the license model, or the mode of distribution of the deliverable. Also services fall under that definition._

**Comment by p-rog** [comment]
The product clarification should be part of the Product Lifecycle definition and also should be included in the product category like we discussed recently. I've adjusted the https://github.com/oasis-tcs/openeox/issues/35 please take a look and comment there if you like it :)

I will try to propose a comprehensive `vendor` definition soon (beginning of September).

**Comment by thschaffr** [comment]
Hello team,

as discussed in the previous meeting, @p-rog and I worked on the following draft proposal for the term `vendor`.
The definition has been closely aligned with the existing definition from [CSAF](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#:~:text=vendor%3A%20the%20community%2C%20individual%2C%20or%20organization%20that%20created%20or%20maintains%20a%20product%20(including%20open%20source%20software%20and%20hardware%20providers)).

>Vendor refers to the community, individual, or organization that created or maintains a product (software, hardware, managed service and other deliverables). This includes, but is not limited to, open-source software and hardware providers.

We are looking forward to the input from the TC.
Thank you.

**Comment by thschaffr** [comment]
The motion to accept the [definition](https://github.com/oasis-tcs/openeox/issues/37#issuecomment-2331325477) above is available at:
https://groups.oasis-open.org/discussion/motion-to-accept-the-vendor-definition
