### ISSUE TITLE
Using "End" word in the lifecycle definitions

### ISSUE THREAD

**Issue by p-rog** [oasis-tcs/openeox#38]
When we worked with @thschaffr on End-of-Maintenance definition (proposal is here https://github.com/oasis-tcs/openeox/issues/29#issuecomment-2332264887), we realized that there is a potential misleading related to the "End" term in our taxonomy and lifecycle definitions. When people see "End", may expect that in the specific lifecycle stage definition there is only one date field, with the last day of something. When it's perfectly fine for End-of-Life (EoL) or End-of-Sales (EoS), it's not necessary the case for Full Support phase or Maintenance support phase. 

We should clarify that in the OpenEoX documentation that some lifecycle stages may overlapping, hence it is necessary to support date ranges. Some lifecycle stages, like proposed  today End-of-Maintenance definition (https://github.com/oasis-tcs/openeox/issues/29#issuecomment-2332264887) provides an optional start date usage.

We decided with @thschaffr  that it would be good to quickly discuss it and make sure that everyone are on the same page and understand that date ranges must be supported in the OpenEoX standard.

**Comment by santosomar** [comment]
The OpenEoX standard should maintain its focus strictly on the end-of-life (EOL) and end-of-support (EOS) stages of product lifecycles. This emphasis aligns with the Technical Committee (TC) charter, which prioritizes creating standardized frameworks for managing and communicating the **final phases** of software and hardware products. The goal is for OpenEoX can provide clear, actionable insights for vendors, maintainers, and users, ensuring consistency and efficiency in product lifecycle management. Expanding beyond this focus would dilute the initiative's core mission and reduce its effectiveness in addressing EOL/EOS challenges in a timely manner.

**Comment by p-rog** [comment]
The main intention of this issue was to raise a potential problem related to the time-frame definition.
We had a really productive discussion today and the conclusion is to focus on the end date of the lifecycle stages. 

I've updated the ` End-of-Maintenance (EoM)` definition proposal accordingly (https://github.com/oasis-tcs/openeox/issues/29#issuecomment-2417411574).

@santosomar do we want to close this issue now to clean the issues list?
